animate1978/MB-Lab

__init__.py

fixed a copy-paste error unregister_class instead of register_class
Signed-off-by: Amir Shehata <amir.shehata@gmail.com>

MB-LAB: Fixed a bug with unregistering the add-on

---

README.md

Since the Manuel Bastioni LAB home page now only shows the following text:
> Development of ManuelbastioniLAB stopped
> Site under construction
I thought it was good to still be able to download the latest official version v1.6.1a. The .zip is hosted on a private cloud, so feel free to upload it somewhere else more public and change the link.

MBLAB website offline, alternative link

---

README.md

Having the last official release manuelbastionilab_161a.zip on the public GitHub cloud seems better to me than my personal cloud. You never know when those stop working, because it is a free account, and also its download speed is not so great.
New link: https://github.com/NumesSanguis/FACSvatar/releases/download/v0.3.4-alpha-release/manuelbastionilab_161a.zip

Change link v1.6.1a to GitHub hosting

---

__init__.py
facerig.py

Added a button to delete the face rig. Some users might prefer to
use the expression sliders, which can not be used after drivers
have been added to the shape keys
Signed-off-by: Amir Shehata <amir.shehata@gmail.com>

MB-Lab: Add the ability to delete the face rig

---

proxyengine.py

avoids an error message from blender (normally not seen, I think) and the possibility of messing up on later vertex groups since we'd otherwise skip appending to the list.

when transferring weights for proxying, check the vertex is in the group.

---

facerig.py

https://docs.python.org/3/library/traceback.html
[flake8](http://flake8.pycqa.org) testing of https://github.com/animate1978/MB-Lab on Python 3.7.1
$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./facerig.py:378:13: F821 undefined name 'traceback'
traceback.print_stack()
^
1     F821 undefined name 'traceback'
1
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: …

Fix undefined name 'traceback' in facerig.py

---

__init__.py
algorithms.py

Additional fix done for menu issue.
After some refactoring in algorithms.py, the file io methods were not imported to access configuration.
Missing import added. Small issue with not displayed face expression properties also fixed.
Warning: 
Operators "mbast.humanoid_rot_limits" and "mbast.delete_rotations" are defined in the menu, but not loaded. The author of this feature should either remove menu items or add operators to classes property in order to load them.

Missing import in algorithms.py added (issue #173)

---

__init__.py
algorithms.py
proxyengine.py

Fixed some things that I felt were missing or broken from the proxy system.
* New option to fit in reverse direction to convert a character-specific mesh to a generic proxy.
* Fixed fitting of meshes that are very close to the skin (basically tested by fitting a trivially modified copy of the body mesh itself).
* New options to do more precise fitting by turning off some normally useful smoothing passes (again, intended basically for alternative body topologies).

Proxy improvements

---

__init__.py

Hi MB-Lab community I'm not a python developer so please double-check my patch but using this in my current usage of MB-Lab so far so good

Fix error while opening library in Assets

---

__init__.py
algorithms.py
creation_tools_ops.py
expressionengine.py
expressionscreator.py
humanoid.py
morphcreator.py
morphengine.py

Conflicts in the merge, attempting to fix

Merge conflict fix attempt

---

__init__.py
expressionscreator.py
morphcreator.py

- Phenotypes creator done.
- Presets creator almost done, need to create files.
- Improved few things, like indent in files.

Character Library Tools (WIP)

---

__init__.py

Fixed error

---

__init__.py
file_ops.py
humanoid.py

In order to separate projects in different folders.
I tried with standard MB-Lab /data/ folder. It seems to work without problem.
But it may have some bugs, probably.

Add "project' drop-down list

---

__init__.py
creation_tools_ops.py

With the new "Project" separation, using the creation tools fails, as the config and blend where handled differently. Now it's good, the creator does nothing for the config, and blend must be in its dedicated folder with the good name.
By the way, this name may change in the future, I think that it's better that it has the name of the project like toon_library.blend, not just humanoid_library.blend.

Fixed a bug for separated projects

---

materialengine.py

My displacement calculation algorithm is faster and uses less memory
1) multiply_images function doesn't seem to be used anywhere so I removed it
2) pixels.foreach_get() is much faster than np.array(pixels)
3) I use in-place array modifications such as += and *= to get rid of excessive data copying and memory allocations
4) reshape(-1) is faster than flatten() and doesn't allocate additional memory
As a result my version is 2x faster, and calculate_disp_pixels function is 18x faster
Before:
```
2021-02-01 17:50:40,307 INFO: MB-Lab.materialengine - calculate_disp_pixels - 155 - start: calculate_disp_pixels human_female_displacement.png
2021-02-01 17:50:44,805 INFO: MB-Lab.materialengine - calculate_disp_pixels - 164 - finish: calculate_disp_pixels human_female_displacement.png
2021-02-01 …
```

Optimize calculate_disp_pixels for faster displacement calculation

---

jointscreator.py
measurescreator.py

Thanks to @regulus_Fen for pointing them out while trying to create his own model.

Bugs chasing in model creation

---

__init__.py

I use debug logger and it gives me a lots of warnings like specified below on startup which is very annoying. 
```
Warning: class MBAST_OT_button_save_body_as_is contains a property which should be an annotation!
/home/upliner/.config/blender/2.91/scripts/addons/MB-Lab/__init__.py:6765
assign as a type annotation: MBAST_OT_button_save_body_as_is.filter_glob
Warning: class MBAST_OT_button_load_base_body contains a property which should be an annotation!
/home/upliner/.config/blender/2.91/scripts/addons/MB-Lab/__init__.py:6765
assign as a type annotation: MBAST_OT_button_load_base_body.filter_glob
```

Use annotations for prop definitions

---

__init__.py

This commit takes out the "HAIR" icon which is broken and made it so the "Hair" section was not appearing in the "ASSETS AND HAIR" panel.  
The panel should now work properly, however, a replacement icon may be preferable on the long term.

Taking out "HAIR" icon so that the hair section works.

---

humanoid.py

Fixed the skin rendering issues

Removed Roughness in humanoid.py

---

CHANGELOG.md
README.md
__init__.py

Final version of MB-Lab as development has moved onto Charmorph
- MB-Lab now requires Blender 4.0.0 +
- UCSS CEL Shader added to Anime models
- MB-Dev tools may contain bugs that are unknown at this time
- Importing BVH animation files is buggy
- Hair presets have the old PrincipledHairBSDF which will result in incorrect rendering
- Skin color and bump mapping change slightly when finalizing

MB-Lab 1.8.1
