- facerig.py
> fix type0 facerig

- .pylintrc
- __init__.py
- algorithms.py
- animationengine.py
- facerig.py
- humanoid.py
- materialengine.py
- morphengine.py
- proxyengine.py
- skeletonengine.py
- Autopep8
- clean algorithms
- clean skeletonengine
- clean proxyengine
- clean morphengine
- clean materialengine
- clean humanoid
- added .pylint
> Clean code, added .pylint

- __init__.py
- algorithms.py
- animationengine.py
- facerig.py
- humanoid.py
- materialengine.py
- morphengine.py
- proxyengine.py
- skeletonengine.py
Replace `algorithms.print_log_report` by python's standard logging system
Closes #33
> replace algorithms print_log_report by pythons logging

- algorithms.py
- materialengine.py
- get_modifier_name to return the name
- fix iter over pixel_arr
Closes #37
> fix finalize

- __init__.py
- algorithms.py
- animationengine.py
- skeletonengine.py
- utils.py
- remove 'self' from args
- moved is_ik_armature, get_active_armature, get_deforming_armature,
get_object_parent to utils.py
- __init__.py uses get_active_armature and is_ik_armature from utils
(previous was algorithms that wasn't imported)
Closes #39
> fix is_ik_armature

- __init__.py
- animationengine.py
- map_main_bones used tuples for mapping bones
- use python f_strings
- cached generate_bones_ids for is_in_side
- @staticmethod's
- bones to dict
- __slots__
ps: before merging to master check if animation is not broken by changes
Closes #42
> 42 clean animation engine

- proxyengine.py
- exception is  RuntimeError not Attribute error
- should fix 46
Issue #46
> fix proxyengine  exception catch

- __init__.py
- algorithms.py
- animationengine.py
- materialengine.py
> rebase #41 remove html commit

- humanoid.py
> fix generate_character

- humanoid.py
Fixed logger messages in humanoid.py
> Fixed logger messages

- .github/ISSUE_TEMPLATE/bug_report.md
If anything, rewrite it to be better. Make sure to explain:
1. How to get the logs
2. How to post the log using the code format (`` `put tildes/backticks around it` ``)
> Include log section.

- addon_updater_ops.py
Fixed updater as per TheDuckCow's suggestion: https://github.com/CGCookie/blender-addon-updater/issues/47#issuecomment-468118438
> Formal Updater Fix

- animationengine.py
Replaced `bpy.context.scene.update()` with `bpy.context.view_layer.update()`
> BVH import bug fix

- CHANGELOG.md
- __init__.py
- addon_updater_ops.py
- animationengine.py
Changed according to docs for addon updater by CGCookie
> Addon_updater_ops.py change to overwrite pattern

- addon_updater_ops.py
I think this helps - It fixes it for me anyway (not a python programmer, apologies if it's not the issue).
> Fix for issues with unregistering classes.

- __init__.py
- algorithms.py
- animationengine.py
- facerig.py
- file_ops.py
- humanoid.py
- materialengine.py
- morphengine.py
- proxyengine.py
- skeletonengine.py
- utils.py
Recovery of the changes deleted with original Dev branch.
@animate1978 please review those changes, those were mostly your changes.
Original branch is preserved here:
https://github.com/mklemarczyk/MB-Lab/commits/dev_old
> Integrate previous changes

- __init__.py
- addon_updater.py
- addon_updater_ops.py
- algorithms.py
- facerig.py
- humanoid.py
- humanoid_rotations.py
- object_ops.py
- proxyengine.py
Resolve issues found by python lint:
Before:
```
28    C901 'start_lab_session' is too complex (13)
4     E111 indentation is not a multiple of four
1     E114 indentation is not a multiple of four (comment)
1     E115 expected an indented block (comment)
3     E116 unexpected indentation (comment)
4     E117 over-indented
2     E122 continuation line missing indentation or outdented
4     E124 closing bracket does not match visual indentation
1     E125 continuation line with same indent as next logical line
24    E127 continuation line over-indented for visual indent
45    E128 continuation line under-indented for visual indent
8     E201 whitespace after '{'
10    E202 whitespace before '}'
1     E211 whitespace before '('
1     E221 multiple spaces before operator
3     E222 multiple …
```
> Resolve trivial code issues

- __init__.py
- creation_tools_ops.py
- expressionengine.py
- expressionscreator.py
- file_ops.py
- morphcreator.py
- morphengine.py
- Morph Creator Updated
- Expression Creator added
- Base engines modified
> Morph and Expression creators

- __init__.py
- algorithms.py
- expressionengine.py
- expressionscreator.py
- morphcreator.py
- All changed files are not necessary related to the tool, few changes are about improvements or changing names.
> Changed Face Expression tool

- __init__.py
- humanoid.py
- morphcreator.py
- Added the possibility to include materials in file (not the materials themselves, just their value).
- Improved also the save of a character by adding indent.
> Presets Creator done.

- __init__.py
- humanoid.py
- morphcreator.py
- transfor.py
It's about the linear interpolation between body shapes and their behavior through age, mass and tone.
Also, corrected a bug in class Humanoid (from me).
> Transformation tool (WIP)

- __init__.py
- morphcreator.py
WIP and saved files just in case, as usual.
But It's almost finished. I just have to figure how to rename a morph when it's a combined one.
And the rescan doesn't work as intended. But the rest of the tool is working (copy, move, delete, backup)
> compy/move/delete morphs tool (WIP)

- __init__.py
- mesh_ops.py
- vgroupscreator.py
> Fixing bugs.

- creation_tools_ops.py
Now if whatever_config.json is under /whatever/, the config loads correctly.
Sorry for the delay.
> Bug about config.json

- algorithms.py
This fixes bugs #297, #302, #305.
> Fix algorithms.apply_modifier() for Blender 2.90

- morphengine.py
Morph correction won't work anyway without bbox data so just skip it for toon girl.
With this change Toon girl finalization works well for me.
> Fix finalization for Toon girl

- algorithms.py
- expressionscreator.py
- file_ops.py
This patch should fix #351 issue
> Fix #351 issues with saving and reloading toon girl
